### ISSUE TITLE
unexpected keyword argument 'n_jobs_rdst'

### ISSUE THREAD

**Issue by xsx-sys** [baraline/convst#38]
When running test_on_arff_resamples.py, the following error occurred. How to solve it?
`PaperScripts/test_on_arff_resamples.py:None (PaperScripts/test_on_arff_resamples.py)
test_on_arff_resamples.py:54: in <module>
    pipeline_RDST_rdg = model_class(n_jobs=3, n_jobs_rdst=100//3)
E   TypeError: __init__() got an unexpected keyword argument 'n_jobs_rdst'`
'

**Comment by baraline** [comment]
Hi, I forgot to update the script to the new API, simply remove n_jobs_rdst argument, and you should be good. The number of job will automatically be balanced by the classifier (i.e. you can put -1 to use all available core on your system).
Note that If you don't have the arff resamples files on your computer, you should use the `test_model.py` script (it is updated to the new API), which will download and produce resample on its own.

I will push an update for the `test_on_arff_resamples.py` script and close the issue, if you got other question don't hesitate !
