### ISSUE TITLE
More options for shapelet sampling

### ISSUE THREAD

**Issue by baraline** [baraline/convst#42]
In some use case, it might be interesting to only sample shapelets from a subset of the input dataset. For example in an imbalanced  binary classification context, if class 0 represent 99% of samples, the majority of shapelets will be sampled from class 0 with the actual random sampling scheme. It might be more interesting to sample shapelets only from class 1 or to downsample class 0.  

While it is simple to add this as a step before doing an RDST transform, it would require reimplementing or hacking through the RDST classifiers.

- [ ] Replace the current `n_samples` parameter of RDST to allow different sampling options, such as :

- Only sample shapelets from a specified subset of the data (boolean mask on samples and/or timestamps)
- String options such as "balanced"
- Current option with float to indicate a percentage for up/downsampling

- [ ] Update API and docs of the rdst transformer and linked classifiers. Clarify which parameter (e.g `class_weight`) impact the classifier and which impact the shapelet sampling.
- [ ] Add unit tests for each options

**Comment by sonal-nu** [comment]
How do i extract distance vector or transformed shapelets for each of my time series?

**Comment by baraline** [comment]
Hi,

There is no option to get the distance vector in the RDST transformer or classifier in the API. 

If you want to have the distance vector resulting from a time series $X$ and a shapelet $S$ (i.e. $d(S,X)$), you can use [this function](https://github.com/baraline/convst/blob/6344cf40dde3178dafaae0ebb8f7ce9f9dc62531/convst/transformers/_commons.py#L301). It takes as input a 1D vector and the parameter of the shapelet, and return the distance vector.
