### ISSUE TITLE
extract distances and transformed shapelets from rdst buildt model

### ISSUE THREAD

**Issue by sonal-nu** [baraline/convst#46]
How do i extract distance vector or transformed shapelets for each of my time series?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by baraline** [comment]
Hi, 

I moved your previous question and my answer in this issue. Did it answer your question ?

--------------------

There is no option to get the distance vector in the RDST transformer or classifier in the API.

If you want to have the distance vector resulting from a time series $X$ and a shapelet $S$ (i.e. $d(S,X)$ ), you can use [this function](https://github.com/baraline/convst/blob/6344cf40dde3178dafaae0ebb8f7ce9f9dc62531/convst/transformers/_commons.py#L301). It takes as input a 1D vector and the parameter of the shapelet, and return the distance vector.

You can also have a look at [the Shapelet class in the RDST Interpreter](https://github.com/baraline/convst/blob/6344cf40dde3178dafaae0ebb8f7ce9f9dc62531/convst/interpreters/rdst_interpreter.py#L23) which is using the function mentioned above.

**Comment by sonal-nu** [comment]
Thanks a bunch this was very helpful. Anyway that I can extract the values of the best match shapelet to my class_id(e.g.1)?

**Comment by sonal-nu** [comment]
I will calculate the distance of the other classes to this shapelets and create a distance matrix from the class 1 to other classes
