### ISSUE TITLE
SystemError: _PyEval_EvalFrameDefault returned a result with an error set

### ISSUE THREAD

**Issue by sonal-nu** [baraline/convst#47]
Working on multivariate time series, with shape (6202x2x33), when running the interpreter model, I am getting this error
SystemError: _PyEval_EvalFrameDefault returned a result with an error set
Please let me know if you need more information
With univariate time series, I dont see the error

**Comment by baraline** [comment]
Closing the issue, feel free to open it again if you want to continue the discussion
